Repository student-kyushu/hibana, pull requests merged in 2019-02, with the labels that each got.

#31 docs: Replace with new email address
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
Labels: S-fails-tests-with-upstream

#32 Install rustfmt with cargo instead of rustup
  .circleci/config.yml
  .travis.yml
Labels: S-awaiting-merge

#33 Improve documents
  .github/CONTRIBUTING.md
  README.md
Labels: S-awaiting-merge

#34 test: Add tests
  Cargo.lock
  src/cmd/new.rs
  tests/integration_test.rs
Labels: S-awaiting-review
